spring:
  application:
    name: user-employee-search

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka
      
ribbon:
   eureka:
     enabled: false
   listOfServers: localhost:8080, localhost:8183
   
server:
  port: 8082
  
app:
  employeeSearch:
    serviceId: employee-search
    endpoint:
      greeting: /employee
      
employee-search:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000
